title: Adria Sartore
short_title: Adria
subtitle: ""
description:
keywords: acrylic, painter, painting, Italian, Italian artist
lang: en
version: 0.0.2
baseurl: ""
url: "https://adriasartore.com"
qr: # 'true' or empty put qr.svg in includes/defs.html call it: icn--qr

company:
  name:  #
  legal_name: #if overrides 'company.name' in footer
  email: adria.sartore@gmail.com
  telephone:
  telephone_whatsapp: #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: https://www.facebook.com/adria.sartore
  youtube:
  instagram: https://www.instagram.com/adria.sartore/
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics:
  verification:

# Build settings
markdown: kramdown
plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
 series:
  output: true
  permalink: /:title/
 pages:
  output: true
  permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: "painting"

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:
