title: Adria Sartore
short_title: Adria
subtitle: ""
description: "My work explores the mysterious world of girls and the mysterious and disturbing feelings from my childhood. My work revolves on the exploration of the most gloomy, secret, disturbing particles of the universal unconscious. Particles we are all familiar with, but that we generally refuse to see. My paintings are like windows or mirrors to access at hidden feelings. Through the creatures of my paintings I want to give form to emotions, like fears and desires, attraction and repulsion."
keywords: acrylic, painter, painting, Italian, Italian artist
lang: en
version: 1.0.1
baseurl: ""
url: "https://adriasartore.com"
qr: true # 'true' or empty put qr.svg in includes/defs.html call it: icn--qr

company:
  name:  #
  legal_name: #if overrides 'company.name' in footer
  email: adria.sartore@gmail.com
  telephone:
  telephone_whatsapp: #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: "https://web.facebook.com/adria.sartore"
  youtube:
  instagram: "https://www.instagram.com/adria.sartore"
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics: G-3XSN68SMQX # < new G4 | > old UA-139930196-1
  verification: lr_EnHIx-rDwgySAru1e6zufUtcu6J5lFdqLUI78fGg

# Build settings
markdown: kramdown
plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
 series:
  output: true
  permalink: /:title/
 years:
  output: true
  permalink: /:title/
 pages:
  output: true
  permalink: /:title/
 about:
  output: true
  permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: "painting"

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:
